// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Remote Controller contributors

import 'dart:io';

import 'package:ffigen/ffigen.dart';

const _symbols = <String>{'rc_get_abi_version', 'rc_get_build_info'};

void main() {
  final packageRoot = Platform.script.resolve('../');
  final header = packageRoot.resolve('native/include/remote_controller_core.h');
  final bindings = packageRoot.resolve(
    'lib/src/third_party/remote_controller_core.g.dart',
  );
  final mapping = packageRoot.resolve(
    'lib/src/third_party/remote_controller_core.record_use_mapping.g.dart',
  );

  final configuredLibclang = Platform.environment['LIBCLANG_PATH'];
  final localLibclang = packageRoot.resolve(
    '.dart_tool/libclang/clang/native/libclang.dll',
  );
  final libclang = configuredLibclang == null
      ? (File.fromUri(localLibclang).existsSync() ? localLibclang : null)
      : Uri.file(configuredLibclang);

  FfiGenerator(
    headers: Headers(entryPoints: <Uri>[header]),
    functions: Functions(
      include: (declaration) => _symbols.contains(declaration.originalName),
      isLeaf: (_) => true,
    ),
    output: Output(
      dartFile: bindings,
      format: true,
      style: const NativeExternalBindings(
        assetId: 'package:remote_controller_core/src/third_party/remote_controller_core.g.dart',
      ),
      preamble: '''
// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Remote Controller contributors
// Generated by package:ffigen. Do not edit manually.
// Regenerate with: dart run tool/ffigen.dart

// ignore_for_file: type=lint, unused_import, unused_element
''',
    ),
  ).generate(libclangDylib: libclang);

  final entries = _symbols.toList()..sort();
  final mappingSource = StringBuffer('''
// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Remote Controller contributors
// Generated by tool/ffigen.dart. Do not edit manually.

const remoteControllerRecordUseMapping = <String, String>{
''');
  for (final symbol in entries) {
    mappingSource.writeln("  '$symbol': '$symbol',");
  }
  mappingSource.writeln('};');
  File.fromUri(mapping).writeAsStringSync(mappingSource.toString());
}
