// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Remote Controller contributors

import 'dart:io';

import 'package:ffigen/ffigen.dart';

const _symbols = <String>{
  'rc_get_abi_version',
  'rc_get_build_info',
  'rc_input_capture_destroy',
  'rc_input_capture_get_snapshot',
  'rc_input_capture_start',
  'rc_input_capture_stop',
  'rc_local_bridge_create',
  'rc_local_bridge_destroy',
  'rc_local_bridge_get_snapshot',
  'rc_local_bridge_start',
  'rc_local_bridge_stop',
  'rc_sdl_capture_create',
  'rc_sdl_enumerate_gamepads',
  'rc_sdl_get_runtime_info',
  'rc_session_create_loopback',
  'rc_session_destroy',
  'rc_session_get_snapshot',
  'rc_session_simulate_disconnect',
  'rc_session_start',
  'rc_session_stop',
  'rc_session_submit_state',
  'rc_vigem_get_runtime_info',
};

const _leafSymbols = <String>{'rc_get_abi_version', 'rc_get_build_info'};

void main() {
  final packageRoot = Platform.script.resolve('../');
  final header = packageRoot.resolve('native/include/remote_controller_core.h');
  final bindings = packageRoot.resolve(
    'lib/src/third_party/remote_controller_core.g.dart',
  );
  final mapping = packageRoot.resolve(
    'lib/src/third_party/remote_controller_core.record_use_mapping.g.dart',
  );

  final configuredLibclang = Platform.environment['LIBCLANG_PATH'];
  final localLibclang = packageRoot.resolve(
    '.dart_tool/libclang/clang/native/libclang.dll',
  );
  final libclang = configuredLibclang == null
      ? (File.fromUri(localLibclang).existsSync() ? localLibclang : null)
      : Uri.file(configuredLibclang);

  FfiGenerator(
    headers: Headers(entryPoints: <Uri>[header]),
    functions: Functions(
      include: (declaration) => _symbols.contains(declaration.originalName),
      isLeaf: (declaration) => _leafSymbols.contains(declaration.originalName),
    ),
    structs: Structs.includeSet({
      'rc_gamepad_state_v1',
      'rc_input_capture_snapshot_v1',
      'rc_input_device_info_v1',
      'rc_local_bridge_snapshot_v1',
      'rc_sdl_runtime_info_v1',
      'rc_session_snapshot_v1',
      'rc_vigem_runtime_info_v1',
    }),
    output: Output(
      dartFile: bindings,
      format: true,
      style: const NativeExternalBindings(
        assetId: 'package:remote_controller_core/src/third_party/remote_controller_core.g.dart',
      ),
      preamble: '''
// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Remote Controller contributors
// Generated by package:ffigen. Do not edit manually.
// Regenerate with: dart run tool/ffigen.dart

// ignore_for_file: type=lint, unused_import, unused_element
''',
    ),
  ).generate(libclangDylib: libclang);

  final entries = _symbols.toList()..sort();
  final mappingSource = StringBuffer('''
// SPDX-License-Identifier: GPL-3.0-only
// Copyright (C) 2026 Remote Controller contributors
// Generated by tool/ffigen.dart. Do not edit manually.

const remoteControllerRecordUseMapping = <String, String>{
''');
  for (final symbol in entries) {
    mappingSource.writeln("  '$symbol': '$symbol',");
  }
  mappingSource.writeln('};');
  File.fromUri(mapping).writeAsStringSync(mappingSource.toString());
}
